services:
  database:
    build:
      context: ./database/
      pull: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "psql -U $${POSTGRES_USER} -d $${POSTGRES_DB} -c 'SELECT 1' || exit 1",
        ]
      interval: 2s
      timeout: 30s
      retries: 30
    restart: unless-stopped
    env_file:
      - .env
      - ${ENV}.env
      - ${ENV}.secrets
      - global.env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USER}
      VERSION: ${VERSION}
    ports:
      - "${DATABASE_PORT}:5432"

  sqitch-migrator:
    depends_on:
      database:
        condition: service_healthy
    restart: on-failure
    build:
      context: ./database/
      dockerfile: Dockerfile.sqitch
      pull: true
    env_file:
      - .env
      - ${ENV}.env
      - ${ENV}.secrets
      - global.env
    environment:
      SQITCH_TARGET: db:pg://${DATABASE_USER}:${DATABASE_PASSWORD}@database:5432/${DATABASE_NAME}
      VERSION: ${VERSION}
