FROM golang:1.25.5-alpine

WORKDIR /source

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY --chown=app:app . .

CMD ["air", "-c", ".air.toml"]
